package com.example.otlhelper.shared.api

import org.junit.Assert.assertEquals
import org.junit.Test

class ApiActionsTest {
    @Test
    fun actionNamesAreUnique() {
        val values = listOf(
            ApiActions.ADD_REACTION,
            ApiActions.APP_STATUS,
            ApiActions.BASE_BULK_INSERT,
            ApiActions.BASE_CLEAR,
            ApiActions.BASE_COUNT,
            ApiActions.BASE_DOWNLOAD,
            ApiActions.BASE_DOWNLOAD_URL,
            ApiActions.BASE_FIND,
            ApiActions.BASE_IMPORT_FULL,
            ApiActions.BASE_SAMPLE,
            ApiActions.BASE_SET_VERSION,
            ApiActions.BASE_VERSION,
            ApiActions.BROADCAST_APP_VERSION,
            ApiActions.CANCEL_SCHEDULED,
            ApiActions.CHANGE_LOGIN,
            ApiActions.CHANGE_PASSWORD,
            ApiActions.CHANGE_ROLE,
            ApiActions.CLEAR_APP_PAUSE,
            ApiActions.CLIENT_DEBUG,
            ApiActions.CREATE_NEWS_POLL,
            ApiActions.CREATE_USER,
            ApiActions.DELETE_MESSAGE,
            ApiActions.DELETE_USER,
            ApiActions.EDIT_MESSAGE,
            ApiActions.GET_ADMIN_CHAT,
            ApiActions.GET_ADMIN_MESSAGES,
            ApiActions.GET_APP_ERRORS,
            ApiActions.GET_APP_STATS,
            ApiActions.GET_APP_VERSION,
            ApiActions.GET_AUDIT_LOG,
            ApiActions.GET_MUTED_CONTACTS,
            ApiActions.GET_NETWORK_STATS,
            ApiActions.GET_NEWS,
            ApiActions.GET_NEWS_READERS,
            ApiActions.GET_POLL_STATS,
            ApiActions.GET_PRESENCE_SNAPSHOT,
            ApiActions.GET_REACTIONS,
            ApiActions.GET_SHEET,
            ApiActions.GET_SYSTEM_STATE,
            ApiActions.GET_UNREAD_COUNTS,
            ApiActions.GET_USER_CHAT,
            ApiActions.GET_USERS,
            ApiActions.HEARTBEAT,
            ApiActions.LIST_DRAFTS,
            ApiActions.LIST_SCHEDULED,
            ApiActions.LIST_SHEETS,
            ApiActions.LOAD_DRAFT,
            ApiActions.LOG_ACTIVITY,
            ApiActions.LOG_ERRORS,
            ApiActions.LOG_METRICS,
            ApiActions.LOGIN,
            ApiActions.LOGOUT,
            ApiActions.MARK_MESSAGE_READ,
            ApiActions.ME,
            ApiActions.MUTE_CONTACT,
            ApiActions.PIN_MESSAGE,
            ApiActions.REBROADCAST_BASE,
            ApiActions.REGISTER_PUSH_TOKEN,
            ApiActions.REMOVE_REACTION,
            ApiActions.RENAME_USER,
            ApiActions.RESET_PASSWORD,
            ApiActions.SAVE_DRAFT,
            ApiActions.SCHEDULE_MESSAGE,
            ApiActions.SEND_MESSAGE,
            ApiActions.SEND_NEWS,
            ApiActions.SET_APP_PAUSE,
            ApiActions.SET_APP_VERSION,
            ApiActions.SET_AVATAR,
            ApiActions.SET_DND_SCHEDULE,
            ApiActions.SOFT_DELETE_MESSAGE,
            ApiActions.TOGGLE_USER,
            ApiActions.UNDELETE_MESSAGE,
            ApiActions.UNMUTE_CONTACT,
            ApiActions.UNPIN_MESSAGE,
            ApiActions.UNREGISTER_PUSH_TOKEN,
            ApiActions.UPDATE_CELL,
            ApiActions.VOTE_NEWS_POLL,
        )
        assertEquals(values.sorted(), values.distinct().sorted())
    }
}
