package com.example.otlhelper.shared.api

/**
 * Server action names shared by Android and desktop clients.
 *
 * Keep this list in sync with `server-modular/index.js`. Client code should
 * reference these constants instead of hardcoded action strings.
 */
object ApiActions {
    const val ADD_REACTION = "add_reaction"
    const val APP_STATUS = "app_status"
    const val BASE_BULK_INSERT = "base_bulk_insert"
    const val BASE_CLEAR = "base_clear"
    const val BASE_COUNT = "base_count"
    const val BASE_DOWNLOAD = "base_download"
    const val BASE_DOWNLOAD_URL = "base_download_url"
    const val BASE_FIND = "base_find"
    const val BASE_IMPORT_FULL = "base_import_full"
    const val BASE_SAMPLE = "base_sample"
    const val BASE_SET_VERSION = "base_set_version"
    const val BASE_VERSION = "base_version"
    const val BROADCAST_APP_VERSION = "broadcast_app_version"
    const val CANCEL_SCHEDULED = "cancel_scheduled"
    const val CHANGE_LOGIN = "change_login"
    const val CHANGE_PASSWORD = "change_password"
    const val CHANGE_ROLE = "change_role"
    const val CLEAR_APP_PAUSE = "clear_app_pause"
    const val CLIENT_DEBUG = "client_debug"
    const val CREATE_NEWS_POLL = "create_news_poll"
    const val CREATE_USER = "create_user"
    const val DELETE_MESSAGE = "delete_message"
    const val DELETE_USER = "delete_user"
    const val EDIT_MESSAGE = "edit_message"
    const val GET_ADMIN_CHAT = "get_admin_chat"
    const val GET_ADMIN_MESSAGES = "get_admin_messages"
    const val GET_APP_ERRORS = "get_app_errors"
    const val GET_APP_STATS = "get_app_stats"
    const val GET_APP_VERSION = "get_app_version"
    const val GET_AUDIT_LOG = "get_audit_log"
    const val GET_MUTED_CONTACTS = "get_muted_contacts"
    const val GET_NETWORK_STATS = "get_network_stats"
    const val GET_NEWS = "get_news"
    const val GET_NEWS_READERS = "get_news_readers"
    const val GET_POLL_STATS = "get_poll_stats"
    const val GET_PRESENCE_SNAPSHOT = "get_presence_snapshot"
    const val GET_REACTIONS = "get_reactions"
    const val GET_SHEET = "get_sheet"
    const val GET_SYSTEM_STATE = "get_system_state"
    const val GET_UNREAD_COUNTS = "get_unread_counts"
    const val GET_USER_CHAT = "get_user_chat"
    const val GET_USERS = "get_users"
    const val HEARTBEAT = "heartbeat"
    const val LIST_DRAFTS = "list_drafts"
    const val LIST_SCHEDULED = "list_scheduled"
    const val LIST_SHEETS = "list_sheets"
    const val LOAD_DRAFT = "load_draft"
    const val LOG_ACTIVITY = "log_activity"
    const val LOG_ERRORS = "log_errors"
    const val LOG_METRICS = "log_metrics"
    const val LOGIN = "login"
    const val LOGOUT = "logout"
    const val MARK_MESSAGE_READ = "mark_message_read"
    const val ME = "me"
    const val MUTE_CONTACT = "mute_contact"
    const val PIN_MESSAGE = "pin_message"
    const val REBROADCAST_BASE = "rebroadcast_base"
    const val REGISTER_PUSH_TOKEN = "register_push_token"
    const val REMOVE_REACTION = "remove_reaction"
    const val RENAME_USER = "rename_user"
    const val RESET_PASSWORD = "reset_password"
    const val SAVE_DRAFT = "save_draft"
    const val SCHEDULE_MESSAGE = "schedule_message"
    const val SEND_MESSAGE = "send_message"
    const val SEND_NEWS = "send_news"
    const val SET_APP_PAUSE = "set_app_pause"
    const val SET_APP_VERSION = "set_app_version"
    const val SET_AVATAR = "set_avatar"
    const val SET_DND_SCHEDULE = "set_dnd_schedule"
    const val SOFT_DELETE_MESSAGE = "soft_delete_message"
    const val TOGGLE_USER = "toggle_user"
    const val UNDELETE_MESSAGE = "undelete_message"
    const val UNMUTE_CONTACT = "unmute_contact"
    const val UNPIN_MESSAGE = "unpin_message"
    const val UNREGISTER_PUSH_TOKEN = "unregister_push_token"
    const val UPDATE_CELL = "update_cell"
    const val VOTE_NEWS_POLL = "vote_news_poll"
}
